apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    url: db:5432
    database: smarthome
    user: smarthome
    secureJsonData:
      password: smarthome
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
