# Generated by Django 5.2.10 on 2026-02-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='value',
            field=models.FloatField(blank=True, help_text='Sensor reading (e.g. 28.5°C, 65% humidity)', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('light', 'Light'), ('ac', 'AC'), ('sensor', 'Sensor'), ('camera', 'Camera'), ('sensor_temp', 'Temperature Sensor'), ('sensor_humidity', 'Humidity Sensor'), ('switch', 'Switch'), ('valve', 'Valve'), ('motor', 'Motor')], max_length=20),
        ),
    ]
