# Generated by Django 5.2.11 on 2026-02-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_device_value_alter_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_controllable',
            field=models.BooleanField(default=False, help_text='Can be toggled on/off'),
        ),
        migrations.AddField(
            model_name='device',
            name='max_value',
            field=models.FloatField(blank=True, help_text='Max threshold for alerts', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='min_value',
            field=models.FloatField(blank=True, help_text='Min threshold for alerts', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Unit (°C, %, V, A, W, pH, ppm, mg/L)', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('pv', 'Solar PV'), ('hydro', 'Hydroponics'), ('fish', 'Fishery')], default='home', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('light', 'Light'), ('ac', 'AC'), ('sensor', 'Sensor'), ('camera', 'Camera'), ('sensor_temp', 'Temperature Sensor'), ('sensor_humidity', 'Humidity Sensor'), ('switch', 'Switch'), ('valve', 'Valve'), ('motor', 'Motor'), ('pv_voltage', 'PV Voltage'), ('pv_current', 'PV Current'), ('pv_power', 'PV Power'), ('pv_energy', 'PV Energy'), ('pv_panel_temp', 'PV Panel Temp'), ('battery_voltage', 'Battery Voltage'), ('battery_soc', 'Battery SoC'), ('battery_current', 'Battery Current'), ('inverter', 'Inverter'), ('grid_power', 'Grid Power'), ('hydro_ph', 'Hydro pH'), ('hydro_ec', 'Hydro EC'), ('hydro_tds', 'Hydro TDS'), ('hydro_water_temp', 'Hydro Water Temp'), ('hydro_water_level', 'Hydro Water Level'), ('hydro_flow', 'Hydro Flow Rate'), ('hydro_light', 'Grow Light'), ('hydro_nutrient_pump', 'Nutrient Pump'), ('hydro_ph_up_pump', 'pH Up Pump'), ('hydro_ph_down_pump', 'pH Down Pump'), ('hydro_main_pump', 'Main Pump'), ('hydro_air_temp', 'Hydro Air Temp'), ('hydro_air_humidity', 'Hydro Air Humidity'), ('fish_water_temp', 'Fish Water Temp'), ('fish_ph', 'Fish pH'), ('fish_do', 'Dissolved Oxygen'), ('fish_ammonia', 'Ammonia'), ('fish_nitrite', 'Nitrite'), ('fish_nitrate', 'Nitrate'), ('fish_turbidity', 'Turbidity'), ('fish_water_level', 'Fish Water Level'), ('fish_aerator', 'Aerator'), ('fish_feeder', 'Auto Feeder'), ('fish_heater', 'Fish Heater'), ('fish_drain_valve', 'Drain Valve'), ('fish_inlet_valve', 'Inlet Valve')], max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='value',
            field=models.FloatField(blank=True, help_text='Sensor reading value', null=True),
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Sensor value')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='dashboard.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='dashboard_s_device__3cfe13_idx'), models.Index(fields=['timestamp'], name='dashboard_s_timesta_64d695_idx')],
            },
        ),
    ]
